---
services:
  nano-bots:
    image: ruby:3.2.2-slim-bookworm
    command: sh -c "apt-get update && apt-get install -y --no-install-recommends build-essential libffi-dev libsodium-dev lua5.4-dev curl && curl -s https://raw.githubusercontent.com/babashka/babashka/master/install | bash && gem install nano-bots -v 3.1.0 && bash"
    environment:
      COHERE_API_KEY: your-api-key

      # GOOGLE_API_KEY: your-api-key

      # GOOGLE_CREDENTIALS_FILE_PATH: /root/.config/google-credentials.json
      # GOOGLE_PROJECT_ID: your-project-id
      GOOGLE_REGION: us-east4

      MARITACA_API_KEY: 'your-api-key'

      MISTRAL_API_KEY: your-api-key

      OLLAMA_API_ADDRESS: http://localhost:11434

      OPENAI_API_KEY: your-access-token

      NANO_BOTS_ENCRYPTION_PASSWORD: UNSAFE
      NANO_BOTS_END_USER: your-user

    volumes:
      - ./google-credentials.json:/root/.config/google-credentials.json
      - ./your-cartridges:/root/.local/share/nano-bots/cartridges
      - ./your-state-path:/root/.local/state/nano-bots

    # If you are running the Ollama server on your localhost:
    # network_mode: host # WARNING: Be careful, this may be a security risk.
