---
safety:
  functions:
    sandboxed: true
  tools:
    confirmable: true

interfaces:
  repl:
    output:
      stream: true
      suffix: "\n"
      prefix: "\n"
    prompt:
      - text: '🤖'
      - text: '> '
  eval:
    output:
      stream: true
      suffix: "\n"
  tools:
    call:
      feedback: true
    response:
      feedback: false

provider:
  settings:
    stream: true
