---
safety:
  functions:
    sandboxed: true
  tools:
    confirmable: true

interfaces:
  repl:
    output:
      stream: true
      prefix: "\n"
      suffix: "\n"
    prompt:
      - text: '🤖'
      - text: '> '
  eval:
    output:
      stream: true
      suffix: "\n"
  tools:
    confirming:
      suffix: ' [yN] '
      default: 'n'
      yeses: ['y', 'yes']
    executing:
      feedback: false
    responding:
      suffix: "\n\n"
      feedback: true

provider:
  options:
    stream: true
  settings:
    stream: true
